"""
Exercise list sourced from FitSW (https://www.fitsw.com/exercise-list/).
Used for search to find workout demonstrations; videos are resolved via YouTube.
"""
EXERCISES = [
    {"name": "Band Hip Abductions", "muscle": "Abductors", "level": "Beginner", "equipment": "Resistance Band"},
    {"name": "Clam", "muscle": "Abductors", "level": "Beginner", "equipment": "None"},
    {"name": "Fire Hydrant", "muscle": "Abductors", "level": "Beginner", "equipment": "None"},
    {"name": "Floor Abductor", "muscle": "Abductors", "level": "Beginner", "equipment": "None"},
    {"name": "Hip Abduction Cable", "muscle": "Abductors", "level": "Beginner", "equipment": "Cable"},
    {"name": "Hip Circles Prone", "muscle": "Abductors", "level": "Beginner", "equipment": "None"},
    {"name": "Side Leg Raise", "muscle": "Abductors", "level": "Beginner", "equipment": "None"},
    {"name": "Standing Hip Circles", "muscle": "Abductors", "level": "Beginner", "equipment": "None"},
    {"name": "Windmills", "muscle": "Abductors", "level": "Intermediate", "equipment": "None"},
    {"name": "3/4 Sit-Up", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Ab Rollouts", "muscle": "Abs", "level": "Intermediate", "equipment": "Ab Wheel"},
    {"name": "Alternate Heel Touchers", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Alternating Abdominal Kick", "muscle": "Abs", "level": "Intermediate", "equipment": "None"},
    {"name": "Alternating Cable Twist", "muscle": "Abs", "level": "Beginner", "equipment": "Cable"},
    {"name": "Angled Side Bridge", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Bicycle Crunches", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Bird Dog", "muscle": "Abs", "level": "Intermediate", "equipment": "None"},
    {"name": "Bent Knee Lying Twist", "muscle": "Abs", "level": "Intermediate", "equipment": "None"},
    {"name": "Bent Knee Side Plank", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Butt-Ups", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Cocoons", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Crunch Hands Overhead", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Crunch Arms Crossed", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Dead Bug", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Decline Sit-up", "muscle": "Abs", "level": "Intermediate", "equipment": "Bench"},
    {"name": "Jumping Jacks", "muscle": "Cardio", "level": "Beginner", "equipment": "None"},
    {"name": "High Knees", "muscle": "Cardio", "level": "Beginner", "equipment": "None"},
    {"name": "Mountain Climbers", "muscle": "Cardio", "level": "Intermediate", "equipment": "None"},
    {"name": "Burpees", "muscle": "Cardio", "level": "Intermediate", "equipment": "None"},
    {"name": "Squat Jumps", "muscle": "Cardio", "level": "Intermediate", "equipment": "None"},
    {"name": "Push-Ups", "muscle": "Chest", "level": "Beginner", "equipment": "None"},
    {"name": "Dumbbell Bench Press", "muscle": "Chest", "level": "Beginner", "equipment": "Dumbbell"},
    {"name": "Incline Push-Up", "muscle": "Chest", "level": "Beginner", "equipment": "None"},
    {"name": "Squats", "muscle": "Quadriceps", "level": "Beginner", "equipment": "None"},
    {"name": "Lunges", "muscle": "Quadriceps", "level": "Beginner", "equipment": "None"},
    {"name": "Leg Raises", "muscle": "Abs", "level": "Beginner", "equipment": "None"},
    {"name": "Plank", "muscle": "Core", "level": "Beginner", "equipment": "None"},
    {"name": "Side Plank", "muscle": "Core", "level": "Beginner", "equipment": "None"},
    {"name": "Glute Bridge", "muscle": "Glutes", "level": "Beginner", "equipment": "None"},
    {"name": "Hip Thrust", "muscle": "Glutes", "level": "Beginner", "equipment": "None"},
    {"name": "Bicep Curls", "muscle": "Biceps", "level": "Beginner", "equipment": "Dumbbell"},
    {"name": "Tricep Dips", "muscle": "Triceps", "level": "Beginner", "equipment": "None"},
    {"name": "Shoulder Press", "muscle": "Shoulders", "level": "Beginner", "equipment": "Dumbbell"},
    {"name": "Lateral Raises", "muscle": "Shoulders", "level": "Beginner", "equipment": "Dumbbell"},
    {"name": "Bent Over Row", "muscle": "Back", "level": "Beginner", "equipment": "Dumbbell"},
    {"name": "Superman", "muscle": "Back", "level": "Beginner", "equipment": "None"},
    {"name": "Calf Raises", "muscle": "Calves", "level": "Beginner", "equipment": "None"},
    {"name": "Hamstring Curls", "muscle": "Hamstrings", "level": "Beginner", "equipment": "None"},
    {"name": "Russian Twist", "muscle": "Abs", "level": "Intermediate", "equipment": "None"},
    {"name": "V-Ups", "muscle": "Abs", "level": "Intermediate", "equipment": "None"},
    {"name": "Box Jumps", "muscle": "Plyometrics", "level": "Intermediate", "equipment": "Box"},
    {"name": "Jump Squats", "muscle": "Plyometrics", "level": "Intermediate", "equipment": "None"},
]
